"""Identity ports — repositories + service Protocols. Pure abstractions."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.identity.domain.entities import OtpCode, OtpPurpose, RefreshToken, User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_oauth(self, provider: str, subject: str) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def update(self, user: User) -> None: ...
    async def schedule_deletion(self, user_id: UUID, scheduled_for: datetime) -> None: ...
    async def cancel_deletion(self, user_id: UUID) -> None: ...
    async def hard_delete(self, user_id: UUID) -> None: ...
    async def get_onboarding_completed(self, user_id: UUID) -> bool:
        """Read the user's onboarding-completed status.

        Lives on ``user_profiles.onboarding_completed`` (profile bounded
        context). Identity reads it at token-issue time so the iOS client
        can route post-login without a second ``GET /me`` round-trip.

        Returns ``False`` if the user has no profile row yet (just-registered).
        """
        ...


class RefreshTokenRepository(Protocol):
    async def add(self, token: RefreshToken) -> None: ...
    async def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    async def revoke(self, token_id: UUID, at: datetime) -> None: ...
    async def revoke_family(self, family_id: UUID, at: datetime) -> int: ...
    async def mark_reused(self, token_id: UUID, at: datetime) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID, at: datetime) -> int:
        """Revoke EVERY non-revoked refresh token belonging to ``user_id``.

        Used by the password-reset flow: changing the password invalidates
        all active sessions on every device (defence against account
        takeover via a leaked credential).

        Returns the number of rows affected (0 when the user had no active
        sessions). Idempotent — already-revoked tokens are not touched.
        """
        ...


class OtpRepository(Protocol):
    async def add(self, otp: OtpCode) -> None: ...
    async def get_active(self, user_id: UUID, purpose: OtpPurpose) -> OtpCode | None: ...
    async def get_active_by_email(self, email: str, purpose: OtpPurpose) -> OtpCode | None: ...
    async def increment_attempts(self, otp_id: UUID) -> int: ...
    async def lock(self, otp_id: UUID, until: datetime) -> None: ...
    async def consume(self, otp_id: UUID) -> None: ...
    async def claim(self, otp_id: UUID) -> bool:
        """Atomic single-use claim. Returns True if THIS caller wins the
        race and the OTP is now consumed, False if another concurrent caller
        already consumed it (or it does not exist).

        Implemented as ``DELETE ... WHERE id = :id RETURNING id`` so two
        concurrent password-reset requests with the same OTP cannot both
        change the password — exactly one wins, the other gets False and
        must be mapped to ``otp_invalid`` by the caller.
        """
        ...


class PasswordHasher(Protocol):
    def hash(self, plain: str) -> str: ...
    def verify(self, plain: str, hashed: str) -> bool: ...


class JwtSigner(Protocol):
    def sign_access(self, *, user_id: UUID, role: str) -> str: ...
    def sign_refresh_value(self) -> str: ...
    def hash_refresh(self, plain: str) -> str: ...
    async def verify_access(self, token: str) -> dict: ...


class OAuthVerifier(Protocol):
    """Protocol shared by Google + Apple verifiers."""

    async def verify_id_token(self, id_token: str) -> dict: ...

    """Returns {sub, email, email_verified, ...} or raises."""
