"""0030 — recipe_components.name_en (English ingredient names, BE-9).

Revision: 0030_recipe_component_name_en
Author:   nova-backend-architect
Date:     2026-07-13

Adds a nullable name_en column to recipe_components and backfills it from
an EMBEDDED ES->EN map (self-contained — no external file read, so the
migration can never crash-loop on a missing data file). Lookup is
case-insensitive on lower(trim(free_text_name)). Rows without a
translation stay NULL; the API falls back to free_text_name (mostly ES).
Idempotent: only fills rows where name_en IS NULL.

Source of truth for edits: data/ingredient_translations_es_en.json
(kept in-repo for reference; this migration embeds a frozen snapshot).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

revision = "0030_recipe_component_name_en"
down_revision = "0029_drop_food_logs_aggregates_daily"
branch_labels = None
depends_on = None

# Frozen ES->EN ingredient translations (708). Embedded on purpose.
_TRANSLATIONS: dict[str, str] = {
    "Aceite de ajonjolí": "Sesame oil",
    "Aceite de coco": "Coconut oil",
    "Aceite de coco (para sartén)": "Coconut oil (for pan)",
    "Aceite de coco en spray": "Coconut oil spray",
    "Aceite de coco o aceite neutro": "Coconut oil or neutral oil",
    "Aceite de oliva": "Olive oil",
    "Aceite de oliva extra virgen": "Extra virgin olive oil",
    "Aceite de sésamo": "Sesame oil",
    "Aceite vegetal": "Vegetable oil",
    "Aceitunas negras sin hueso": "Pitted black olives",
    "Aceitunas negras sin hueso rebanadas": "Sliced pitted black olives",
    "Aceitunas verdes o negras sin semilla": "Pitted green or black olives",
    "Aceitunas verdes sin semilla": "Pitted green olives",
    "Acelgas": "Swiss chard",
    "Agua": "Water",
    "Agua fría": "Cold water",
    "Agua o caldo bajo en sodio": "Water or low-sodium broth",
    "Agua o caldo de res bajo en sodio": "Water or low-sodium beef broth",
    "Aguacate": "Avocado",
    "Aguacate en rebanadas": "Sliced avocado",
    "Aguacate maduro": "Ripe avocado",
    "Aguacate maduro en cubos": "Diced ripe avocado",
    "Aguacate maduro en rebanadas": "Sliced ripe avocado",
    "Aguacate maduro en rodajas": "Sliced ripe avocado",
    "Aguacate maduro pelado sin hueso": "Ripe avocado, peeled and pitted",
    "Ajo": "Garlic",
    "Ajo en polvo": "Garlic powder",
    "Ajo fresco": "Fresh garlic",
    "Ajo picado fino": "Finely minced garlic",
    "Albahaca fresca": "Fresh basil",
    "Albahaca seca": "Dried basil",
    "Alcaparras": "Capers",
    "Alcaparras en salmuera escurridas": "Drained brined capers",
    "Almendras": "Almonds",
    "Almendras crudas": "Raw almonds",
    "Almendras enteras": "Whole almonds",
    "Almendras laminadas": "Sliced almonds",
    "Almendras picadas": "Chopped almonds",
    "Apio": "Celery",
    "Apio en rodajas": "Sliced celery",
    "Apio en trozos": "Chopped celery",
    "Arandano": "Blueberry",
    "Arroz blanco": "White rice",
    "Arroz blanco cocido": "Cooked white rice",
    "Arroz blanco crudo": "Raw white rice",
    "Arroz blanco de grano corto": "Short-grain white rice",
    "Arroz integral": "Brown rice",
    "Arroz integral cocido": "Cooked brown rice",
    "Arroz integral crudo": "Raw brown rice",
    "Arroz jazmín cocido": "Cooked jasmine rice",
    "Arveja (guisante) congelada": "Frozen peas",
    "Arveja verde": "Green peas",
    "Arvejas": "Peas",
    "Arvejas (guisantes) frescos o congelados": "Fresh or frozen peas",
    "Arándanos": "Blueberries",
    "Arándanos congelados": "Frozen blueberries",
    "Arándanos frescos": "Fresh blueberries",
    "Arándanos frescos o congelados": "Fresh or frozen blueberries",
    "Arándanos secos": "Dried cranberries",
    "Arándanos secos sin azúcar": "Unsweetened dried cranberries",
    "Atún claro en agua": "Light tuna in water",
    "Atún en agua": "Tuna in water",
    "Atún en agua (escurrido)": "Tuna in water (drained)",
    "Atún en agua en lata": "Canned tuna in water",
    "Atún en agua escurrido": "Drained tuna in water",
    "Atún en agua, escurrido": "Tuna in water, drained",
    "Atún en lata": "Canned tuna",
    "Avena en hojuelas": "Rolled oats",
    "Avena en hojuelas (molida)": "Rolled oats (ground)",
    "Avena en hojuelas gruesas": "Thick rolled oats",
    "Avena en hojuelas seca": "Dry rolled oats",
    "Azúcar (para reducir acidez)": "Sugar (to reduce acidity)",
    "Batata": "Sweet potato",
    "Batata (camote) en cubos": "Diced sweet potato",
    "Batata (camote) en cubos de 2cm": "Sweet potato in 2cm cubes",
    "Batata (camote) pelada": "Peeled sweet potato",
    "Batata en cubos": "Diced sweet potato",
    "Berenjena": "Eggplant",
    "Berenjena en cubos": "Diced eggplant",
    "Bistec de res (falda o palomilla)": "Beef steak (flank or top sirloin)",
    "Bistec de res (sirloin)": "Beef steak (sirloin)",
    "Brócoli": "Broccoli",
    "Brócoli en floretes": "Broccoli florets",
    "Brócoli en floretes pequeños": "Small broccoli florets",
    "Brócoli en ramitos": "Broccoli florets",
    "Brócoli en ramitos pequeños": "Small broccoli florets",
    "Brócoli en trozos": "Broccoli pieces",
    "Brócoli en trozos pequeños": "Small broccoli pieces",
    "Cacahuates": "Peanuts",
    "Cacao en polvo": "Cocoa powder",
    "Cacao en polvo sin azúcar": "Unsweetened cocoa powder",
    "Calabacita": "Zucchini",
    "Calabacín": "Zucchini",
    "Calabacín (zucchini)": "Zucchini",
    "Calabaza": "Squash",
    "Calamar limpio en aros": "Cleaned squid rings",
    "Caldo de pescado o agua con sal": "Fish broth or salted water",
    "Caldo de pollo": "Chicken broth",
    "Caldo de pollo bajo en sal": "Low-salt chicken broth",
    "Caldo de pollo bajo en sodio": "Low-sodium chicken broth",
    "Caldo de pollo o agua": "Chicken broth or water",
    "Caldo de pollo o vegetales": "Chicken or vegetable broth",
    "Caldo de res": "Beef broth",
    "Caldo de res bajo en sodio": "Low-sodium beef broth",
    "Caldo de vegetales": "Vegetable broth",
    "Caldo de vegetales bajo en sodio": "Low-sodium vegetable broth",
    "Caldo de verduras bajo en sodio": "Low-sodium vegetable broth",
    "Camarones limpios sin cáscara": "Cleaned peeled shrimp",
    "Camarones limpios y pelados": "Cleaned and peeled shrimp",
    "Camarones medianos pelados y limpios": "Medium peeled and cleaned shrimp",
    "Camarones pelados y limpios": "Peeled and cleaned shrimp",
    "Camarón": "Shrimp",
    "Camote": "Sweet potato",
    "Camote (batata)": "Sweet potato",
    "Canela": "Cinnamon",
    "Canela en polvo": "Ground cinnamon",
    "Canela molida": "Ground cinnamon",
    "Carne de carne de res en cubos (carne de res para guisar)": "Diced beef (stewing beef)",
    "Carne de carne de res en cubos (pulpa o lomo)": "Diced beef (round or loin)",
    "Carne de cerdo en cubos": "Diced pork",
    "Carne de cerdo en cubos pequeños": "Small diced pork",
    "Carne de res (corte magro, sin grasa visible)": "Beef (lean cut, no visible fat)",
    "Carne de res (corte sin grasa visible)": "Beef (cut with no visible fat)",
    "Carne de res (sin grasa visible)": "Beef (no visible fat)",
    "Carne de res en tiras delgadas": "Beef in thin strips",
    "Carne de res para guisar": "Stewing beef",
    "Carne de res para guisar en cubos": "Diced stewing beef",
    "Carne molida de cerdo": "Ground pork",
    "Carne molida de res": "Ground beef",
    "Carne molida de res magra": "Lean ground beef",
    "Cebolla": "Onion",
    "Cebolla blanca": "White onion",
    "Cebolla blanca en cubos": "Diced white onion",
    "Cebolla blanca en picado fino": "Finely chopped white onion",
    "Cebolla blanca en rebanadas delgadas": "Thinly sliced white onion",
    "Cebolla blanca picada": "Chopped white onion",
    "Cebolla blanca picada fina": "Finely chopped white onion",
    "Cebolla de cambray (cebollín)": "Green onion",
    "Cebolla de verdeo (cebollín) picada": "Chopped green onion",
    "Cebolla en cuartos": "Quartered onion",
    "Cebolla en cubos": "Diced onion",
    "Cebolla en polvo": "Onion powder",
    "Cebolla en rodajas delgadas": "Thinly sliced onion",
    "Cebolla en rodajas finas": "Thinly sliced onion",
    "Cebolla en tiras delgadas": "Onion in thin strips",
    "Cebolla morada": "Red onion",
    "Cebolla morada en rodajas delgadas": "Thinly sliced red onion",
    "Cebolla morada en rodajas finas": "Thinly sliced red onion",
    "Cebolla morada en tiras delgadas": "Red onion in thin strips",
    "Cebolla morada picada fina": "Finely chopped red onion",
    "Cebolla morada picada fino": "Finely chopped red onion",
    "Cebolla picada": "Chopped onion",
    "Cebolla picada fina": "Finely chopped onion",
    "Cebolla picada fino": "Finely chopped onion",
    "Cebolla roja picada fina": "Finely chopped red onion",
    "Cebollín": "Green onion",
    "Cebollín fresco": "Fresh green onion",
    "Cebollín picado": "Chopped green onion",
    "Cebollín picado fino": "Finely chopped green onion",
    "Cerdo molido magro": "Lean ground pork",
    "Cerezas congeladas sin hueso": "Frozen pitted cherries",
    "Champiñones": "Mushrooms",
    "Champiñones en láminas": "Sliced mushrooms",
    "Champiñones en rodajas": "Sliced mushrooms",
    "Champiñones frescos": "Fresh mushrooms",
    "Champiñones frescos rebanados": "Fresh sliced mushrooms",
    "Champiñones portobello en láminas": "Sliced portobello mushrooms",
    "Champiñón": "Mushroom",
    "Chayote": "Chayote",
    "Chayote o calabacín en cubos": "Diced chayote or zucchini",
    "Chile en polvo": "Chili powder",
    "Chorizo bajo en grasa en rodajas": "Sliced low-fat chorizo",
    "Chuño": "Chuño (freeze-dried potato)",
    "Cilantro": "Cilantro",
    "Cilantro fresco": "Fresh cilantro",
    "Cilantro fresco picado": "Chopped fresh cilantro",
    "Cilantro o perejil fresco": "Fresh cilantro or parsley",
    "Clara de huevo": "Egg white",
    "Claras de huevo": "Egg whites",
    "Claras de huevo pasteurizadas": "Pasteurized egg whites",
    "Coco rallado": "Grated coconut",
    "Coco rallado sin azúcar": "Unsweetened grated coconut",
    "Col": "Cabbage",
    "Col blanca rallada": "Shredded white cabbage",
    "Cola de langosta": "Lobster tail",
    "Coliflor": "Cauliflower",
    "Coliflor en floretes": "Cauliflower florets",
    "Coliflor en trozos": "Cauliflower pieces",
    "Comino": "Cumin",
    "Comino en polvo": "Ground cumin",
    "Comino molido": "Ground cumin",
    "Comino y cúrcuma": "Cumin and turmeric",
    "Comino y orégano": "Cumin and oregano",
    "Crema ligera (15% grasa)": "Light cream (15% fat)",
    "Crema light": "Light cream",
    "Curry en polvo": "Curry powder",
    "Cuscús": "Couscous",
    "Cuscús integral": "Whole wheat couscous",
    "Cúrcuma": "Turmeric",
    "Cúrcuma en polvo": "Ground turmeric",
    "Cúrcuma molida": "Ground turmeric",
    "Durazno": "Peach",
    "Durazno fresco": "Fresh peach",
    "Durazno maduro pelado sin hueso": "Ripe peach, peeled and pitted",
    "Dátiles Medjool sin semilla": "Pitted Medjool dates",
    "Edamame": "Edamame",
    "Edamame (habas de soya) cocidas": "Cooked edamame (soybeans)",
    "Edamame cocido": "Cooked edamame",
    "Ejotes": "Green beans",
    "Elote": "Corn",
    "Eneldo fresco": "Fresh dill",
    "Eneldo fresco picado fino": "Finely chopped fresh dill",
    "Espinaca": "Spinach",
    "Espinaca fresca": "Fresh spinach",
    "Espinacas": "Spinach",
    "Espinacas baby": "Baby spinach",
    "Espinacas baby frescas": "Fresh baby spinach",
    "Espinacas frescas": "Fresh spinach",
    "Espinacas picadas": "Chopped spinach",
    "Espirulina en polvo (alga verde)": "Spirulina powder (green algae)",
    "Espárrago": "Asparagus",
    "Espárragos": "Asparagus",
    "Espárragos frescos": "Fresh asparagus",
    "Espárragos frescos troceados": "Chopped fresh asparagus",
    "Extracto de vainilla": "Vanilla extract",
    "Extracto de vainilla puro": "Pure vanilla extract",
    "Fideos de arroz": "Rice noodles",
    "Fideos de cabello de ángel o fideos finos": "Angel hair or thin noodles",
    "Fideos de huevo cocidos": "Cooked egg noodles",
    "Fideos de sopa medianos": "Medium soup noodles",
    "Fideos de trigo (tipo vermicelli)": "Wheat noodles (vermicelli type)",
    "Fideos de trigo delgados": "Thin wheat noodles",
    "Fideos finos": "Thin noodles",
    "Filete de atún fresco": "Fresh tuna fillet",
    "Filete de pescado blanco": "White fish fillet",
    "Filete de pescado blanco fresco": "Fresh white fish fillet",
    "Filete de res magro (lomo)": "Lean beef fillet (loin)",
    "Filete de salmón": "Salmon fillet",
    "Filete de salmón sin piel": "Skinless salmon fillet",
    "Frambuesa": "Raspberry",
    "Frambuesas": "Raspberries",
    "Frambuesas congeladas": "Frozen raspberries",
    "Frambuesas frescas o congeladas": "Fresh or frozen raspberries",
    "Fresa": "Strawberry",
    "Fresas": "Strawberries",
    "Fresas frescas": "Fresh strawberries",
    "Fresas frescas o congeladas": "Fresh or frozen strawberries",
    "Frijol negro cocido": "Cooked black beans",
    "Frijoles blancos cocidos": "Cooked white beans",
    "Frijoles negros cocidos": "Cooked black beans",
    "Frijoles negros cocidos (de lata, escurridos)": "Cooked black beans (canned, drained)",
    "Frijoles negros cocidos (en lata, escurridos)": "Cooked black beans (canned, drained)",
    "Frijoles pintos cocidos": "Cooked pinto beans",
    "Frutos rojos mixtos (fresa, arándano, frambuesa)": "Mixed berries (strawberry, blueberry, raspberry)",
    "Galletas de avena": "Oat cookies",
    "Garbanzo cocido": "Cooked chickpeas",
    "Garbanzos cocidos": "Cooked chickpeas",
    "Garbanzos cocidos (de lata, escurridos)": "Cooked chickpeas (canned, drained)",
    "Garbanzos cocidos (en lata, escurridos)": "Cooked chickpeas (canned, drained)",
    "Garbanzos cocidos en lata": "Canned cooked chickpeas",
    "Germen de trigo": "Wheat germ",
    "Granola": "Granola",
    "Granola de avena y nueces": "Oat and walnut granola",
    "Granola sin azúcar": "Sugar-free granola",
    "Granola sin azúcar añadida": "Granola with no added sugar",
    "Granos de maíz": "Corn kernels",
    "Guayaba": "Guava",
    "Guayaba madura pelada": "Ripe peeled guava",
    "Guisantes (arvejas) congelados": "Frozen peas",
    "Habas de soya cocidas (edamame)": "Cooked soybeans (edamame)",
    "Habas de soya cocido sin vaina": "Cooked shelled soybeans",
    "Habichuelas (vainitas) verdes": "Green beans",
    "Harina de avena": "Oat flour",
    "Harina de maíz": "Corn flour",
    "Hielo": "Ice",
    "Hierbas frescas": "Fresh herbs",
    "Hojas de menta": "Mint leaves",
    "Hojas de menta fresca": "Fresh mint leaves",
    "Huevo": "Egg",
    "Huevo duro (2 piezas)": "Hard-boiled egg (2 pieces)",
    "Huevo entero": "Whole egg",
    "Huevo entero (3 piezas)": "Whole egg (3 pieces)",
    "Huevos enteros": "Whole eggs",
    "Hummus": "Hummus",
    "Hummus natural": "Plain hummus",
    "Jamón de pavo bajo en grasa en cubos": "Diced low-fat turkey ham",
    "Jengibre": "Ginger",
    "Jengibre en polvo": "Ground ginger",
    "Jengibre fresco": "Fresh ginger",
    "Jengibre fresco rallado": "Grated fresh ginger",
    "Jitomate": "Tomato",
    "Jitomates cherry": "Cherry tomatoes",
    "Judías verdes": "Green beans",
    "Jugo de limón": "Lime juice",
    "Jugo de limón verde": "Lime juice",
    "Jugo de naranja natural": "Fresh orange juice",
    "Jícama": "Jicama",
    "Kiwi": "Kiwi",
    "Kiwi pelado": "Peeled kiwi",
    "Leche": "Milk",
    "Leche de almendra": "Almond milk",
    "Leche de almendra sin azúcar": "Unsweetened almond milk",
    "Leche de avena sin azúcar": "Unsweetened oat milk",
    "Leche de coco": "Coconut milk",
    "Leche de coco light": "Light coconut milk",
    "Leche descremada": "Skim milk",
    "Leche descremada (para puré)": "Skim milk (for purée)",
    "Leche descremada adicional para la base": "Additional skim milk for the base",
    "Leche descremada caliente": "Warm skim milk",
    "Leche descremada fría": "Cold skim milk",
    "Leche entera": "Whole milk",
    "Leche entera o semidescremada": "Whole or reduced-fat milk",
    "Leche semidescremada": "Reduced-fat milk",
    "Lechuga": "Lettuce",
    "Lechuga en trozos": "Chopped lettuce",
    "Lechuga romana": "Romaine lettuce",
    "Lechuga romana en hojas": "Romaine lettuce leaves",
    "Lechuga romana en tiras": "Shredded romaine lettuce",
    "Lechuga romana en trozos": "Chopped romaine lettuce",
    "Lenteja cocida": "Cooked lentils",
    "Lentejas cocidas": "Cooked lentils",
    "Lentejas naranjas (rojas) secas": "Dried red lentils",
    "Lentejas rojas cocidas": "Cooked red lentils",
    "Lentejas rojas crudas": "Raw red lentils",
    "Lentejas rojas secas": "Dried red lentils",
    "Lentejas verdes secas": "Dried green lentils",
    "Limón": "Lime",
    "Lomo de cerdo": "Pork loin",
    "Lomo de cerdo en cubos": "Diced pork loin",
    "Lomo de cerdo en tiras delgadas": "Pork loin in thin strips",
    "Lomo de cerdo magro en rodajas gruesas de 2cm": "Lean pork loin in 2cm thick slices",
    "Lomo de res en medallones": "Beef loin medallions",
    "Lomo de res magro en tiras delgadas": "Lean beef loin in thin strips",
    "Lomo de res sin grasa visible": "Beef loin with no visible fat",
    "Maicena (almidón de maíz)": "Cornstarch",
    "Mango": "Mango",
    "Mango deshidratado": "Dried mango",
    "Mango fresco en cubos": "Diced fresh mango",
    "Mango maduro": "Ripe mango",
    "Mango maduro en cubos pequeños": "Small-diced ripe mango",
    "Mango maduro pelado": "Peeled ripe mango",
    "Mantequilla": "Butter",
    "Mantequilla de almendra natural": "Natural almond butter",
    "Mantequilla de maní": "Peanut butter",
    "Mantequilla de maní natural": "Natural peanut butter",
    "Mantequilla de maní natural (sin azúcar)": "Natural peanut butter (unsweetened)",
    "Mantequilla de maní natural sin azúcar": "Unsweetened natural peanut butter",
    "Mantequilla sin sal": "Unsalted butter",
    "Manzana": "Apple",
    "Manzana con cascara": "Apple with skin",
    "Manzana con piel": "Apple with skin",
    "Manzana rallada": "Grated apple",
    "Manzana roja en rodajas": "Sliced red apple",
    "Manzana roja o verde": "Red or green apple",
    "Manzana verde": "Green apple",
    "Manzana verde sin piel ni semillas": "Green apple, peeled and seeded",
    "Manzana verde sin semillas": "Green apple, seeds removed",
    "Masa de pizza integral": "Whole wheat pizza dough",
    "Masa de pizza integral (base delgada comprada)": "Whole wheat pizza dough (store-bought thin crust)",
    "Mayonesa light": "Light mayonnaise",
    "Maíz (maíz) en rodajas": "Sliced corn",
    "Maíz desgranado": "Corn kernels",
    "Mejillones limpios": "Cleaned mussels",
    "Melón verde tipo honeydew pelado sin semillas": "Honeydew melon, peeled and seeded",
    "Menta fresca": "Fresh mint",
    "Menta fresca (opcional)": "Fresh mint (optional)",
    "Miel": "Honey",
    "Miel de abeja": "Honey",
    "Miel de abeja o azúcar morena": "Honey or brown sugar",
    "Moras congeladas": "Frozen blackberries",
    "Mostaza": "Mustard",
    "Mostaza Dijon": "Dijon mustard",
    "Mozzarella light rallada": "Grated light mozzarella",
    "Muesli sin azúcar añadida": "Muesli with no added sugar",
    "Muslo de pollo sin piel": "Skinless chicken thigh",
    "Naranja": "Orange",
    "Nopal": "Nopal (cactus)",
    "Nueces": "Walnuts",
    "Nueces de castilla": "Walnuts",
    "Nueces picadas": "Chopped walnuts",
    "Orégano seco": "Dried oregano",
    "Pan de centeno": "Rye bread",
    "Pan integral": "Whole wheat bread",
    "Pan integral (rebanadas)": "Whole wheat bread (slices)",
    "Pan integral de molde": "Whole wheat sandwich bread",
    "Pan integral rallado": "Whole wheat breadcrumbs",
    "Pan integral tostado": "Toasted whole wheat bread",
    "Pan pita integral": "Whole wheat pita bread",
    "Papa": "Potato",
    "Papa blanca": "White potato",
    "Papa blanca en cubos": "Diced white potato",
    "Papa blanca en cubos pequeños": "Small-diced white potato",
    "Papa blanca pelada": "Peeled white potato",
    "Papa blanca pelada en trozos": "Peeled white potato, chopped",
    "Papa cocida en cubos pequeños": "Small-diced cooked potato",
    "Papa dulce (batata) en rodajas": "Sliced sweet potato",
    "Papa en cuartos": "Quartered potato",
    "Papa en cubos medianos": "Medium-diced potato",
    "Papa mediana": "Medium potato",
    "Papa mediana cocida": "Cooked medium potato",
    "Papas pequeñas": "Small potatoes",
    "Papaya": "Papaya",
    "Papaya madura pelada sin semillas": "Ripe papaya, peeled and seeded",
    "Paprika": "Paprika",
    "Pasas": "Raisins",
    "Pasas sin semillas": "Seedless raisins",
    "Pasta": "Pasta",
    "Pasta integral": "Whole wheat pasta",
    "Pasta integral (ditalini o espirales)": "Whole wheat pasta (ditalini or spirals)",
    "Pasta integral (espagueti o linguine)": "Whole wheat pasta (spaghetti or linguine)",
    "Pasta integral (espagueti o penne)": "Whole wheat pasta (spaghetti or penne)",
    "Pasta integral (penne o espagueti)": "Whole wheat pasta (penne or spaghetti)",
    "Pasta integral (penne o espiral)": "Whole wheat pasta (penne or spirals)",
    "Pasta integral (penne o fusilli)": "Whole wheat pasta (penne or fusilli)",
    "Pasta integral (penne)": "Whole wheat pasta (penne)",
    "Pasta integral cocida": "Cooked whole wheat pasta",
    "Pasta integral pequeña (coditos o ditalini)": "Small whole wheat pasta (elbows or ditalini)",
    "Pasta integral tipo espagueti": "Whole wheat spaghetti",
    "Pavo molido": "Ground turkey",
    "Pavo molido bajo en grasa": "Low-fat ground turkey",
    "Pechuga de pavo": "Turkey breast",
    "Pechuga de pavo cocida en cubos": "Diced cooked turkey breast",
    "Pechuga de pavo en láminas": "Sliced turkey breast",
    "Pechuga de pavo en rebanadas": "Sliced turkey breast",
    "Pechuga de pavo molida o en trozos pequeños": "Ground or small-chopped turkey breast",
    "Pechuga de pavo sin piel": "Skinless turkey breast",
    "Pechuga de pollo": "Chicken breast",
    "Pechuga de pollo cocida desmenuzada": "Cooked shredded chicken breast",
    "Pechuga de pollo cocida y desmenuzada": "Cooked and shredded chicken breast",
    "Pechuga de pollo en cubos": "Diced chicken breast",
    "Pechuga de pollo en cubos de 2cm": "Chicken breast in 2cm cubes",
    "Pechuga de pollo en trozos": "Chopped chicken breast",
    "Pechuga de pollo entera": "Whole chicken breast",
    "Pechuga de pollo grande sin piel": "Large skinless chicken breast",
    "Pechuga de pollo sin piel": "Skinless chicken breast",
    "Pechuga de pollo sin piel (entera)": "Skinless chicken breast (whole)",
    "Pechuga de pollo sin piel cocida y desmenuzada": "Cooked and shredded skinless chicken breast",
    "Pepino": "Cucumber",
    "Pepino con cascara": "Cucumber with skin",
    "Pepino en cubos": "Diced cucumber",
    "Pepino en medias lunas": "Half-moon sliced cucumber",
    "Pepino en rodajas": "Sliced cucumber",
    "Pepino en rodajas finas": "Thinly sliced cucumber",
    "Pepino fresco pelado": "Fresh peeled cucumber",
    "Pepitas de calabaza": "Pumpkin seeds",
    "Pera con cascara": "Pear with skin",
    "Perejil fresco": "Fresh parsley",
    "Perejil fresco picado": "Chopped fresh parsley",
    "Perejil fresco picado fino": "Finely chopped fresh parsley",
    "Pescado blanco": "White fish",
    "Pescado de río": "River fish",
    "Pimentón ahumado": "Smoked paprika",
    "Pimentón dulce": "Sweet paprika",
    "Pimentón dulce (paprika)": "Sweet paprika",
    "Pimentón dulce en polvo": "Ground sweet paprika",
    "Pimiento": "Bell pepper",
    "Pimiento amarillo": "Yellow bell pepper",
    "Pimiento amarillo picado": "Chopped yellow bell pepper",
    "Pimiento rojo": "Red bell pepper",
    "Pimiento rojo en cubos": "Diced red bell pepper",
    "Pimiento rojo en cubos pequeños": "Small-diced red bell pepper",
    "Pimiento rojo en tiras delgadas": "Red bell pepper in thin strips",
    "Pimiento rojo en tiras delgadass": "Red bell pepper in thin strips",
    "Pimiento rojo en trozos": "Chopped red bell pepper",
    "Pimiento rojo o verde grande": "Large red or green bell pepper",
    "Pimiento rojo picado": "Chopped red bell pepper",
    "Pimiento rojo picado fino": "Finely chopped red bell pepper",
    "Pimiento rojo y verde en cubos": "Diced red and green bell pepper",
    "Pimiento verde": "Green bell pepper",
    "Pimiento verde en cubos": "Diced green bell pepper",
    "Pimiento verde picado": "Chopped green bell pepper",
    "Piña": "Pineapple",
    "Piña fresca en trozos": "Fresh pineapple chunks",
    "Piña fresca o en conserva sin azúcar": "Fresh or unsweetened canned pineapple",
    "Plátano": "Banana",
    "Plátano banano": "Banana",
    "Plátano congelado": "Frozen banana",
    "Plátano maduro": "Ripe banana",
    "Plátano maduro congelado": "Frozen ripe banana",
    "Plátano maduro en rodajas": "Sliced ripe banana",
    "Pollo cocido desmechado": "Cooked shredded chicken",
    "Polvo para hornear": "Baking powder",
    "Proteína de suero sabor chocolate": "Chocolate whey protein",
    "Proteína de suero sabor chocolate o neutro": "Chocolate or unflavored whey protein",
    "Proteína de suero sabor chocolate o vainilla": "Chocolate or vanilla whey protein",
    "Proteína de suero sabor fresa o vainilla": "Strawberry or vanilla whey protein",
    "Proteína de suero sabor natural o vainilla": "Plain or vanilla whey protein",
    "Proteína de suero sabor vainilla": "Vanilla whey protein",
    "Proteína de suero sabor vainilla o caramelo": "Vanilla or caramel whey protein",
    "Proteína de suero sabor vainilla o coco": "Vanilla or coconut whey protein",
    "Proteína de suero sabor vainilla o fresa": "Vanilla or strawberry whey protein",
    "Proteína de suero sabor vainilla o mango": "Vanilla or mango whey protein",
    "Proteína de suero sabor vainilla o neutro": "Vanilla or unflavored whey protein",
    "Proteína en polvo": "Protein powder",
    "Proteína en polvo sabor chocolate": "Chocolate protein powder",
    "Proteína en polvo sabor chocolate o vainilla": "Chocolate or vanilla protein powder",
    "Proteína en polvo sabor fresa o vainilla": "Strawberry or vanilla protein powder",
    "Proteína en polvo sabor vainilla": "Vanilla protein powder",
    "Proteína en polvo sabor vainilla o coco": "Vanilla or coconut protein powder",
    "Proteína en polvo sabor vainilla o tropical": "Vanilla or tropical protein powder",
    "Pulpa de maracuyá (maracuyá abierta y colada)": "Passion fruit pulp (strained)",
    "Pulpo limpio cocido": "Cleaned cooked octopus",
    "Páprika": "Paprika",
    "Páprika ahumada": "Smoked paprika",
    "Queso bajo en grasa en láminas": "Sliced low-fat cheese",
    "Queso bajo en grasa rallado": "Grated low-fat cheese",
    "Queso cheddar bajo en grasa rallado": "Grated low-fat cheddar cheese",
    "Queso cottage bajo en grasa": "Low-fat cottage cheese",
    "Queso cottage descremado": "Nonfat cottage cheese",
    "Queso crema bajo en grasa": "Low-fat cream cheese",
    "Queso de cabra desmenuzado": "Crumbled goat cheese",
    "Queso de hebra": "String cheese",
    "Queso feta desmenuzado": "Crumbled feta cheese",
    "Queso fresco": "Fresh cheese",
    "Queso fresco bajo en grasa": "Low-fat fresh cheese",
    "Queso mozzarella bajo en grasa": "Low-fat mozzarella cheese",
    "Queso mozzarella bajo en grasa rallado": "Grated low-fat mozzarella cheese",
    "Queso panela": "Panela cheese",
    "Queso parmesano rallado": "Grated parmesan cheese",
    "Queso ricotta bajo en grasa": "Low-fat ricotta cheese",
    "Quinoa": "Quinoa",
    "Quinoa cocida": "Cooked quinoa",
    "Quinoa cruda": "Raw quinoa",
    "Quinua cocida": "Cooked quinoa",
    "Ralladura de limón": "Lime zest",
    "Ralladura de naranja": "Orange zest",
    "Rebanada de queso bajo en grasa": "Low-fat cheese slice",
    "Requeson bajo en grasa": "Low-fat curd cheese",
    "Requesón bajo en grasa": "Low-fat curd cheese",
    "Romero fresco o seco": "Fresh or dried rosemary",
    "Romero seco": "Dried rosemary",
    "Rúcula fresca": "Fresh arugula",
    "Sal": "Salt",
    "Salmón": "Salmon",
    "Salmón ahumado": "Smoked salmon",
    "Salmón ahumado en trozos": "Smoked salmon pieces",
    "Salmón en trozo": "Salmon piece",
    "Salsa de soya": "Soy sauce",
    "Salsa de soya baja en sodio": "Low-sodium soy sauce",
    "Salsa de tomate natural sin azúcar": "Natural tomato sauce, unsweetened",
    "Salvado de avena": "Oat bran",
    "Sandía": "Watermelon",
    "Sardinas en lata": "Canned sardines",
    "Semilla de chia": "Chia seeds",
    "Semilla de chía": "Chia seeds",
    "Semilla de linaza molida": "Ground flaxseed",
    "Semillas de ajonjolí": "Sesame seeds",
    "Semillas de ajonjolí tostadas": "Toasted sesame seeds",
    "Semillas de calabaza": "Pumpkin seeds",
    "Semillas de chía": "Chia seeds",
    "Semillas de girasol": "Sunflower seeds",
    "Semillas de linaza": "Flaxseed",
    "Semillas de lino molidas": "Ground flaxseed",
    "Semillas de sésamo": "Sesame seeds",
    "Sirloin de res magro": "Lean beef sirloin",
    "Tahini (pasta de sésamo)": "Tahini (sesame paste)",
    "Tofu firme": "Firm tofu",
    "Tofu firme en cubos de 2cm": "Firm tofu in 2cm cubes",
    "Tomate": "Tomato",
    "Tomate cherry": "Cherry tomato",
    "Tomate cherry cortado a la mitad": "Halved cherry tomato",
    "Tomate cherry cortado por la mitad": "Halved cherry tomato",
    "Tomate cherry partido a la mitad": "Halved cherry tomato",
    "Tomate en cubos": "Diced tomato",
    "Tomate en rebanadas": "Sliced tomato",
    "Tomate en rodajas": "Sliced tomato",
    "Tomate maduro": "Ripe tomato",
    "Tomate maduro en rebanadas": "Sliced ripe tomato",
    "Tomate mediano": "Medium tomato",
    "Tomate picado": "Chopped tomato",
    "Tomate picado fino": "Finely chopped tomato",
    "Tomate rojo": "Red tomato",
    "Tomate triturado": "Crushed tomato",
    "Tomate triturado en lata": "Canned crushed tomato",
    "Tomate triturado natural": "Natural crushed tomato",
    "Tomates cherry": "Cherry tomatoes",
    "Tomates maduros": "Ripe tomatoes",
    "Tomates maduros en trozos": "Chopped ripe tomatoes",
    "Tomates maduros picados": "Chopped ripe tomatoes",
    "Tomates pera maduros triturados": "Crushed ripe plum tomatoes",
    "Tomates pera triturados": "Crushed plum tomatoes",
    "Tomates triturados": "Crushed tomatoes",
    "Tomates triturados en lata": "Canned crushed tomatoes",
    "Tomillo fresco": "Fresh thyme",
    "Tomillo seco": "Dried thyme",
    "Tortilla de harina integral (30g c/u)": "Whole wheat flour tortilla (30g each)",
    "Tortilla de maíz": "Corn tortilla",
    "Tortilla de trigo integral": "Whole wheat tortilla",
    "Tortilla integral de trigo": "Whole wheat tortilla",
    "Tortilla integral grande": "Large whole wheat tortilla",
    "Tortilla integral grande (30cm)": "Large whole wheat tortilla (30cm)",
    "Tortillas de maíz": "Corn tortillas",
    "Tortillas de maíz pequeñas": "Small corn tortillas",
    "Tostadas de maíz": "Corn tostadas",
    "Vainilla en extracto": "Vanilla extract",
    "Vinagre blanco (para pochar)": "White vinegar (for poaching)",
    "Vino tinto seco": "Dry red wine",
    "Yogur bajo en grasa": "Low-fat yogurt",
    "Yogur griego descremado": "Nonfat Greek yogurt",
    "Yogur griego natural 0%": "Plain Greek yogurt 0%",
    "Yogur griego natural 0% grasa": "Plain Greek yogurt 0% fat",
    "Yogur griego natural sin azúcar": "Unsweetened plain Greek yogurt",
    "Yogur griego natural sin azúcar 0% grasa": "Unsweetened plain Greek yogurt 0% fat",
    "Yogur griego natural sin azúcar 2% grasa": "Unsweetened plain Greek yogurt 2% fat",
    "Yogur griego natural sin grasa": "Nonfat plain Greek yogurt",
    "Yogur griego sin grasa": "Nonfat Greek yogurt",
    "Yuca": "Cassava",
    "Zanahoria": "Carrot",
    "Zanahoria en bastones": "Carrot sticks",
    "Zanahoria en cubos": "Diced carrot",
    "Zanahoria en rodajas": "Sliced carrot",
    "Zanahoria en rodajas gruesas": "Thickly sliced carrot",
    "Zanahoria en tiras delgadass": "Carrot in thin strips",
    "Zanahoria en trozos": "Chopped carrot",
    "Zanahoria en trozos gruesos": "Coarsely chopped carrot",
    "Zanahoria rallada": "Grated carrot",
    "Zanahorias": "Carrots",
    "Zucchini": "Zucchini",
    "Zucchini (calabacín) en cubos": "Diced zucchini",
    "Zucchini en cubos pequeños": "Small-diced zucchini",
    "Zucchini en medias lunas": "Half-moon sliced zucchini",
    "Zucchini en rodajas gruesas": "Thickly sliced zucchini",
    "Zucchini rallado": "Grated zucchini",
    "bistec de res": "Beef steak",
    "carne molida de res (90% magra)": "Ground beef (90% lean)",
    "chile guajillo": "Guajillo chili",
    "chuleta de cerdo": "Pork chop",
    "lentejas": "Lentils",
    "lomo de res": "Beef loin",
    "maíz tierno": "Sweet corn",
    "nopales": "Nopales (cactus)",
    "pierna de cerdo": "Pork leg",
    "pimiento morrón": "Bell pepper",
    "tomate verde (tomatillo)": "Tomatillo",
    "Aceite de oliva en spray": "Olive oil spray",
    "Aceite en spray": "Cooking oil spray",
    "Ajo en polvo y jengibre en polvo": "Garlic powder and ground ginger",
    "Ajo en polvo y sal": "Garlic powder and salt",
    "Ajo en polvo, orégano, sal y pimienta": "Garlic powder, oregano, salt and pepper",
    "Ajo en polvo, paprika dulce, sal y pimienta": "Garlic powder, sweet paprika, salt and pepper",
    "Ajo en polvo, paprika, sal y pimienta": "Garlic powder, paprika, salt and pepper",
    "Ajo en polvo, sal y comino": "Garlic powder, salt and cumin",
    "Ajo en polvo, sal y pimienta negra": "Garlic powder, salt and black pepper",
    "Ajo en polvo, sal, pimienta y perejil": "Garlic powder, salt, pepper and parsley",
    "Ajo en polvo, tomillo, sal y pimienta": "Garlic powder, thyme, salt and pepper",
    "Ajo picado": "Minced garlic",
    "Albahaca fresca o seca": "Fresh or dried basil",
    "Bacalao (pescado blanco)": "Cod (white fish)",
    "Chile jalapeño": "Jalapeño pepper",
    "Chile seco en hojuelas (opcional)": "Dried chili flakes (optional)",
    "Cilantro fresco y jugo de limón": "Fresh cilantro and lime juice",
    "Comino y orégano seco": "Cumin and dried oregano",
    "Comino, pimentón ahumado y cúrcuma": "Cumin, smoked paprika and turmeric",
    "Comino, sal y cilantro": "Cumin, salt and cilantro",
    "Comino, sal y pimienta": "Cumin, salt and pepper",
    "Cubos de hielo": "Ice cubes",
    "Cúrcuma, comino, sal y pimienta": "Turmeric, cumin, salt and pepper",
    "Eneldo seco o fresco": "Dried or fresh dill",
    "Eneldo seco, sal y pimienta": "Dried dill, salt and pepper",
    "Filete de pescado blanco (tilapia, corvina o similar)": "White fish fillet (tilapia, sea bass or similar)",
    "Hoja de laurel": "Bay leaf",
    "Jugo de limón, sal y pimienta": "Lime juice, salt and pepper",
    "Laurel y tomillo": "Bay leaf and thyme",
    "Nuez moscada": "Nutmeg",
    "Orégano y albahaca seca": "Oregano and dried basil",
    "Orégano y laurel": "Oregano and bay leaf",
    "Orégano, sal y pimienta": "Oregano, salt and pepper",
    "Perejil fresco, sal y pimienta": "Fresh parsley, salt and pepper",
    "Perejil seco": "Dried parsley",
    "Pimentón ahumado, sal y pimienta": "Smoked paprika, salt and pepper",
    "Pimienta negra": "Black pepper",
    "Ralladura de lima": "Lime zest",
    "Romero seco o fresco": "Dried or fresh rosemary",
    "Romero, sal y pimienta": "Rosemary, salt and pepper",
    "Romero, tomillo, sal y pimienta": "Rosemary, thyme, salt and pepper",
    "Sal gruesa, pimienta negra y ajo en polvo": "Coarse salt, black pepper and garlic powder",
    "Sal marina y pimienta roja molida": "Sea salt and ground red pepper",
    "Sal y comino": "Salt and cumin",
    "Sal y pimienta": "Salt and pepper",
    "Sal y pimienta blanca": "Salt and white pepper",
    "Sal y pimienta negra": "Salt and black pepper",
    "Sal, pimienta blanca y nuez moscada": "Salt, white pepper and nutmeg",
    "Sal, pimienta negra y comino": "Salt, black pepper and cumin",
    "Sal, pimienta negra y sésamo": "Salt, black pepper and sesame",
    "Sal, pimienta y ajo en polvo": "Salt, pepper and garlic powder",
    "Sal, pimienta y azúcar (pizca)": "Salt, pepper and sugar (pinch)",
    "Sal, pimienta y chile en hojuelas": "Salt, pepper and chili flakes",
    "Sal, pimienta y chile en polvo": "Salt, pepper and chili powder",
    "Sal, pimienta y cilantro": "Salt, pepper and cilantro",
    "Sal, pimienta y cilantro fresco": "Salt, pepper and fresh cilantro",
    "Sal, pimienta y comino": "Salt, pepper and cumin",
    "Sal, pimienta y comino molido": "Salt, pepper and ground cumin",
    "Sal, pimienta y eneldo seco": "Salt, pepper and dried dill",
    "Sal, pimienta y laurel": "Salt, pepper and bay leaf",
    "Sal, pimienta y nuez moscada": "Salt, pepper and nutmeg",
    "Sal, pimienta y orégano": "Salt, pepper and oregano",
    "Sal, pimienta y orégano seco": "Salt, pepper and dried oregano",
    "Sal, pimienta y paprika": "Salt, pepper and paprika",
    "Sal, pimienta y perejil": "Salt, pepper and parsley",
    "Sal, pimienta y perejil fresco": "Salt, pepper and fresh parsley",
    "Sal, pimienta y perejil picado": "Salt, pepper and chopped parsley",
    "Sal, pimienta y páprika": "Salt, pepper and paprika",
    "Sal, pimienta y semillas de sésamo": "Salt, pepper and sesame seeds",
    "Sal, pimienta, cilantro y orégano": "Salt, pepper, cilantro and oregano",
    "Sal, pimienta, cúrcuma y orégano": "Salt, pepper, turmeric and oregano",
    "Sal, pimienta, paprika y palillos de madera": "Salt, pepper, paprika and wooden skewers",
    "Tilapia": "Tilapia",
    "Tomillo seco, ajo en polvo, sal y pimienta": "Dried thyme, garlic powder, salt and pepper",
}


def upgrade() -> None:
    op.add_column("recipe_components", sa.Column("name_en", sa.Text(), nullable=True))
    conn = op.get_bind()
    index = {k.strip().lower(): v for k, v in _TRANSLATIONS.items()}
    for es_lower, en in index.items():
        conn.execute(
            text(
                """
                UPDATE recipe_components
                   SET name_en = :en
                 WHERE name_en IS NULL
                   AND lower(trim(free_text_name)) = :es
                """
            ),
            {"en": en, "es": es_lower},
        )


def downgrade() -> None:
    op.drop_column("recipe_components", "name_en")
